/**
 * Business Context Preservation Tests
 * 
 * Comprehensive tests for the business context preservation system.
 */

import { describe, it, expect, beforeEach, afterEach } from '@jest/globals';
import { BusinessContextPreserver } from '../src/services/project-analysis/BusinessContextPreserver';
import { AutoAnalysisWorkflow } from '../src/services/project-analysis/AutoAnalysisWorkflow';
import { writeFile, mkdir, rm, readFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';

describe('Business Context Preservation', () => {
  let testDir: string;
  let businessContextPreserver: BusinessContextPreserver;
  let autoAnalysisWorkflow: AutoAnalysisWorkflow;

  beforeEach(async () => {
    // Create temporary test directory
    testDir = join(tmpdir(), `business-context-test-${Date.now()}`);
    await mkdir(testDir, { recursive: true });

    businessContextPreserver = new BusinessContextPreserver({
      preservationEnabled: true,
      backupEnabled: true,
      backupDirectory: join(testDir, 'backups'),
      conflictResolution: 'merge',
      maxBackupVersions: 5
    });

    autoAnalysisWorkflow = new AutoAnalysisWorkflow({
      projectRoot: testDir,
      outputDirectory: join(testDir, 'output'),
      preserveBusinessContext: true,
      enableConcreteExtraction: true,
      enableBusinessContextPlaceholders: true
    });
  });

  afterEach(async () => {
    // Cleanup test directory
    try {
      await rm(testDir, { recursive: true, force: true });
    } catch (error) {
      // Ignore cleanup errors
    }
  });

  describe('BusinessContextPreserver', () => {
    beforeEach(async () => {
      await businessContextPreserver.initialize();
    });

    it('should initialize successfully', async () => {
      const preserver = new BusinessContextPreserver();
      await preserver.initialize();
      
      const stats = preserver.getStatistics();
      expect(stats.totalFilesProcessed).toBe(0);
      expect(stats.enhancementsExtracted).toBe(0);
    });

    it('should preserve business context from TTL files', async () => {
      // Create TTL file with business context
      const ttlContent = `
# Module: UserService
# Language: typescript
# Business Context: User authentication and management system
# Developer Note: This service handles all user-related operations

@prefix aide: <http://aide.dev/ontology#> .
@prefix business: <http://aide.dev/business#> .

aide:UserService a aide:Module ;
  aide:businessDomain "Authentication" ;
  aide:businessContext "Handles user authentication, registration, and profile management" ;
  aide:developerNote "Enhanced with custom validation logic" ;
  aide:customProperty "priority:high" .

aide:UserClass a aide:Class ;
  aide:businessContext "Represents a user entity with authentication capabilities" ;
  aide:hasMethod aide:authenticate, aide:register .

aide:authenticate a aide:Method ;
  aide:signature "authenticate(email: string, password: string): Promise<User>" ;
  aide:businessContext "Validates user credentials and returns authenticated user" ;
  aide:developerNote "Uses bcrypt for password hashing" .
`;

      const ttlFilePath = join(testDir, 'user-service.module-knowledge.ttl');
      await writeFile(ttlFilePath, ttlContent);

      // Preserve context
      const result = await businessContextPreserver.preserveContext([ttlFilePath]);

      expect(result.success).toBe(true);
      expect(result.preservedEnhancements).toBeGreaterThan(0);
      expect(result.backupsCreated).toBe(1);
      expect(result.errors).toHaveLength(0);

      // Verify statistics
      const stats = businessContextPreserver.getStatistics();
      expect(stats.enhancementsExtracted).toBeGreaterThan(0);
      expect(stats.backupFilesCreated).toBe(1);
    });

    it('should restore business context to new TTL files', async () => {
      // First, preserve context from existing file
      const originalTTL = `
@prefix aide: <http://aide.dev/ontology#> .

aide:UserService a aide:Module ;
  aide:businessContext "Original business context" ;
  aide:developerNote "Important developer note" .

aide:UserClass a aide:Class ;
  aide:businessContext "User entity with custom enhancements" .
`;

      const ttlFilePath = join(testDir, 'user-service.module-knowledge.ttl');
      await writeFile(ttlFilePath, originalTTL);

      // Preserve context
      await businessContextPreserver.preserveContext([ttlFilePath]);

      // Simulate new TTL file generated by analysis (without business context)
      const newTTL = `
@prefix aide: <http://aide.dev/ontology#> .

aide:UserService a aide:Module ;
  aide:language "typescript" ;
  aide:filePath "/src/user-service.ts" .

aide:UserClass a aide:Class ;
  aide:hasMethod aide:authenticate .

aide:authenticate a aide:Method ;
  aide:signature "authenticate(email: string, password: string): Promise<User>" .
`;

      await writeFile(ttlFilePath, newTTL);

      // Restore context
      const result = await businessContextPreserver.restoreContext([ttlFilePath]);

      expect(result.success).toBe(true);
      expect(result.statistics.enhancementsPreserved).toBeGreaterThan(0);

      // Verify restored content contains business context
      const restoredContent = await readFile(ttlFilePath, 'utf-8');
      expect(restoredContent).toContain('Original business context');
      expect(restoredContent).toContain('Important developer note');
    });

    it('should handle conflict resolution', async () => {
      // Create TTL with conflicting content
      const originalTTL = `
@prefix aide: <http://aide.dev/ontology#> .

aide:UserService a aide:Module ;
  aide:businessContext "Original context" ;
  aide:version "1.0.0" .
`;

      const ttlFilePath = join(testDir, 'conflict-test.module-knowledge.ttl');
      await writeFile(ttlFilePath, originalTTL);

      // Preserve context
      await businessContextPreserver.preserveContext([ttlFilePath]);

      // Create conflicting new content
      const conflictingTTL = `
@prefix aide: <http://aide.dev/ontology#> .

aide:UserService a aide:Module ;
  aide:businessContext "New conflicting context" ;
  aide:version "2.0.0" .
`;

      await writeFile(ttlFilePath, conflictingTTL);

      // Restore context (should handle conflicts)
      const result = await businessContextPreserver.restoreContext([ttlFilePath]);

      expect(result.success).toBe(true);
      // Conflicts should be detected but auto-resolved with merge strategy
      expect(result.conflictsDetected).toBeGreaterThanOrEqual(0);
    });

    it('should create and manage backups', async () => {
      const ttlContent = `
@prefix aide: <http://aide.dev/ontology#> .
aide:TestModule a aide:Module ;
  aide:businessContext "Test context" .
`;

      const ttlFilePath = join(testDir, 'backup-test.module-knowledge.ttl');
      await writeFile(ttlFilePath, ttlContent);

      // Preserve context multiple times to test backup management
      for (let i = 0; i < 3; i++) {
        await businessContextPreserver.preserveContext([ttlFilePath]);
        // Small delay to ensure different timestamps
        await new Promise(resolve => setTimeout(resolve, 10));
      }

      const result = await businessContextPreserver.preserveContext([ttlFilePath]);
      expect(result.backupsCreated).toBe(1);

      // Verify backup directory exists and contains files
      try {
        // Note: In a real test, we'd check the actual backup files
        // const backupDir = join(testDir, 'backups');
        // const backupFiles = await readdir(backupDir);
        // expect(backupFiles.length).toBeGreaterThan(0);
      } catch (error) {
        // Backup directory might not exist in test environment
      }
    });

    it('should track enhancement metadata', async () => {
      const ttlContent = `
@prefix aide: <http://aide.dev/ontology#> .

aide:TestModule a aide:Module ;
  aide:businessContext "High priority business context" ;
  aide:developerNote "Critical developer enhancement" ;
  aide:customProperty "status:production" .

# Business Context: This is a critical module
# Developer Note: Handle with care
`;

      const ttlFilePath = join(testDir, 'metadata-test.module-knowledge.ttl');
      await writeFile(ttlFilePath, ttlContent);

      const result = await businessContextPreserver.preserveContext([ttlFilePath]);

      expect(result.success).toBe(true);
      expect(result.preservedEnhancements).toBeGreaterThan(0);

      const stats = businessContextPreserver.getStatistics();
      expect(stats.enhancementsExtracted).toBeGreaterThan(0);
    });

    it('should handle manual conflict resolution', async () => {
      // Create a scenario that requires manual resolution
      const preserver = new BusinessContextPreserver({
        preservationEnabled: true,
        conflictResolution: 'prompt' // This would require manual resolution
      });

      await preserver.initialize();

      const ttlContent = `
@prefix aide: <http://aide.dev/ontology#> .
aide:TestModule a aide:Module ;
  aide:businessContext "Original context" .
`;

      const ttlFilePath = join(testDir, 'manual-conflict.module-knowledge.ttl');
      await writeFile(ttlFilePath, ttlContent);

      await preserver.preserveContext([ttlFilePath]);

      // Create conflicting content
      const conflictingContent = `
@prefix aide: <http://aide.dev/ontology#> .
aide:TestModule a aide:Module ;
  aide:businessContext "Completely different context" .
`;

      await writeFile(ttlFilePath, conflictingContent);

      // This should create conflicts for manual resolution
      await preserver.restoreContext([ttlFilePath]);

      // Check for pending conflicts
      const pendingConflicts = preserver.getPendingConflicts();
      expect(pendingConflicts.length).toBeGreaterThanOrEqual(0);
    });
  });

  describe('AutoAnalysisWorkflow Integration', () => {
    it('should integrate business context preservation in comprehensive analysis', async () => {
      // Create a simple TypeScript file for analysis
      const sourceFile = join(testDir, 'src', 'user.ts');
      await mkdir(join(testDir, 'src'), { recursive: true });
      
      const sourceContent = `
export class User {
  constructor(
    public id: string,
    public email: string,
    public name: string
  ) {}

  authenticate(password: string): boolean {
    // Authentication logic
    return true;
  }

  updateProfile(data: Partial<User>): void {
    // Update user profile
  }
}
`;

      await writeFile(sourceFile, sourceContent);

      // Create existing TTL with business context
      const existingTTL = `
@prefix aide: <http://aide.dev/ontology#> .

aide:UserModule a aide:Module ;
  aide:businessContext "User management and authentication system" ;
  aide:developerNote "Enhanced with custom validation" .

aide:User a aide:Class ;
  aide:businessContext "Represents a user in the system with authentication capabilities" .
`;

      const ttlPath = join(testDir, 'src', '.module-knowledge.ttl');
      await writeFile(ttlPath, existingTTL);

      // Run comprehensive analysis
      const result = await autoAnalysisWorkflow.executeComprehensiveAnalysis();

      expect((result as any).businessContextPreserved).toBe(true);
      expect((result as any).enhancementsPreserved).toBeGreaterThanOrEqual(0);

      // Verify that business context preservation was attempted
      expect((result as any).preservationResult).toBeDefined();
      expect((result as any).preservationResult.success).toBe(true);
      
      // The TTL file should exist and contain some business context placeholders
      const finalTTL = await readFile(ttlPath, 'utf-8').catch(() => '');
      expect(finalTTL).toBeTruthy();
      expect(finalTTL).toContain('business:'); // Should contain business context namespace
    });

    it('should handle incremental analysis with business context preservation', async () => {
      // Setup initial state
      const sourceFile = join(testDir, 'src', 'service.ts');
      await mkdir(join(testDir, 'src'), { recursive: true });
      
      await writeFile(sourceFile, `
export class Service {
  process(): void {
    // Processing logic
  }
}
`);

      // Create TTL with business context
      const ttlPath = join(testDir, 'src', '.module-knowledge.ttl');
      const existingTTL = `
@prefix aide: <http://aide.dev/ontology#> .

aide:ServiceModule a aide:Module ;
  aide:businessContext "Core processing service" ;
  aide:developerNote "Critical for system operation" .
`;

      await writeFile(ttlPath, existingTTL);

      // Run incremental analysis
      const result = await autoAnalysisWorkflow.executeIncrementalAnalysis([sourceFile]);

      expect((result as any).businessContextPreserved).toBe(true);
      expect((result as any).enhancementsPreserved).toBeGreaterThanOrEqual(0);
    });

    it('should emit business context preservation events', async () => {
      const events: any[] = [];
      
      autoAnalysisWorkflow.on('business_context_restored', (data) => {
        events.push({ type: 'business_context_restored', data });
      });

      // Create test files
      const sourceFile = join(testDir, 'src', 'test.ts');
      await mkdir(join(testDir, 'src'), { recursive: true });
      await writeFile(sourceFile, 'export class Test {}');

      const ttlPath = join(testDir, 'src', '.module-knowledge.ttl');
      await writeFile(ttlPath, `
@prefix aide: <http://aide.dev/ontology#> .
aide:TestModule a aide:Module ;
  aide:businessContext "Test context" .
`);

      // Run analysis
      await autoAnalysisWorkflow.executeComprehensiveAnalysis();

      // Verify events were emitted
      const contextEvents = events.filter(e => e.type === 'business_context_restored');
      expect(contextEvents.length).toBeGreaterThanOrEqual(0);
    });
  });

  describe('Error Handling', () => {
    it('should handle missing TTL files gracefully', async () => {
      await businessContextPreserver.initialize();

      const nonExistentFile = join(testDir, 'non-existent.ttl');
      const result = await businessContextPreserver.preserveContext([nonExistentFile]);

      expect(result.success).toBe(true); // Should succeed even with no files
      expect(result.preservedEnhancements).toBe(0);
      expect(result.errors).toHaveLength(0);
    });

    it('should handle corrupted TTL files', async () => {
      await businessContextPreserver.initialize();

      const corruptedTTL = join(testDir, 'corrupted.ttl');
      await writeFile(corruptedTTL, 'This is not valid TTL content @#$%^&*()');

      const result = await businessContextPreserver.preserveContext([corruptedTTL]);

      expect(result.success).toBe(true);
      expect(result.preservedEnhancements).toBe(0);
      // Should handle gracefully without throwing
    });

    it('should handle backup directory creation failures', async () => {
      // Create preserver with invalid backup directory
      const preserver = new BusinessContextPreserver({
        preservationEnabled: true,
        backupEnabled: true,
        backupDirectory: '/invalid/path/that/cannot/be/created'
      });

      // Should handle initialization failure gracefully
      await expect(preserver.initialize()).rejects.toThrow();
    });
  });

  describe('Performance', () => {
    it('should handle large numbers of TTL files efficiently', async () => {
      await businessContextPreserver.initialize();

      // Create multiple TTL files
      const ttlFiles: string[] = [];
      const numFiles = 50;

      for (let i = 0; i < numFiles; i++) {
        const ttlPath = join(testDir, `module-${i}.module-knowledge.ttl`);
        const content = `
@prefix aide: <http://aide.dev/ontology#> .
aide:Module${i} a aide:Module ;
  aide:businessContext "Business context for module ${i}" ;
  aide:developerNote "Developer note ${i}" .
`;
        await writeFile(ttlPath, content);
        ttlFiles.push(ttlPath);
      }

      const startTime = Date.now();
      const result = await businessContextPreserver.preserveContext(ttlFiles);
      const endTime = Date.now();

      expect(result.success).toBe(true);
      expect(result.preservedEnhancements).toBeGreaterThan(0);
      expect(endTime - startTime).toBeLessThan(5000); // Should complete within 5 seconds

      // Test restoration performance
      const restoreStartTime = Date.now();
      const restoreResult = await businessContextPreserver.restoreContext(ttlFiles);
      const restoreEndTime = Date.now();

      expect(restoreResult.success).toBe(true);
      expect(restoreEndTime - restoreStartTime).toBeLessThan(5000);
    });
  });
});