/**
 * Enhanced MCP Server Integration
 * 
 * Integrates the TTLContextLoader with the existing MCP server to provide
 * automatic context loading from TTL files generated by the analysis system.
 */

import { EventEmitter } from 'events';
import logger from '../../utils/logger';
import { MCPServer } from './MCPServer';
import { TTLContextLoader } from './TTLContextLoader';
import { KnowledgeGraphPopulator } from '../project-analysis/KnowledgeGraphPopulator';
import { EnhancedRDFGenerator } from '../layer1/rdf-generator/EnhancedRDFGenerator';
import { ConcreteInformationExtractor } from '../layer1/rdf-generator/ConcreteInformationExtractor';
import { Layer3AIService } from '../layer3/index';
import { HybridStorageManager } from '../layer2/hybrid-storage/HybridStorageManager';
import {
  ContextRequest,
  ContextResponse,
  EnhancedMCPServerConfig,
  EnhancedMCPServerMetrics,
  TTLIntegrationEvent
} from './types';

/**
 * Enhanced MCP Server with automatic TTL context loading
 */
export class EnhancedMCPServer extends EventEmitter {
  private mcpServer: MCPServer;
  private ttlContextLoader: TTLContextLoader;
  private _knowledgeGraphPopulator: KnowledgeGraphPopulator;
  private _rdfGenerator: EnhancedRDFGenerator;
  private _informationExtractor: ConcreteInformationExtractor;
  
  private config: EnhancedMCPServerConfig;
  private metrics: EnhancedMCPServerMetrics;
  private isRunning: boolean = false;

  constructor(
    config: EnhancedMCPServerConfig,
    layer3Service: Layer3AIService,
    hybridStorage: HybridStorageManager,
    knowledgeGraphPopulator: KnowledgeGraphPopulator,
    rdfGenerator: EnhancedRDFGenerator,
    informationExtractor: ConcreteInformationExtractor
  ) {
    super();
    
    this.config = config;
    this._knowledgeGraphPopulator = knowledgeGraphPopulator;
    this._rdfGenerator = rdfGenerator;
    this._informationExtractor = informationExtractor;
    
    // Initialize base MCP server
    this.mcpServer = new MCPServer(
      config.mcpServer,
      layer3Service,
      hybridStorage
    );
    
    // Initialize TTL context loader
    this.ttlContextLoader = new TTLContextLoader(
      config.ttlContextLoader,
      this._knowledgeGraphPopulator,
      this._rdfGenerator,
      this._informationExtractor
    );
    
    this.metrics = this.initializeMetrics();
    this.setupEventHandlers();
    
    logger.info('EnhancedMCPServer initialized', {
      mcpServerPort: config.mcpServer.server.port,
      ttlWatchEnabled: config.ttlContextLoader.watchEnabled
    });
  }

  /**
   * Initialize metrics
   */
  private initializeMetrics(): EnhancedMCPServerMetrics {
    return {
      server: {
        uptime: 0,
        totalRequests: 0,
        enhancedContextRequests: 0,
        ttlContextRequests: 0,
        averageResponseTime: 0,
        errorRate: 0
      },
      ttlIntegration: {
        ttlFilesLoaded: 0,
        contextCacheHits: 0,
        contextCacheMisses: 0,
        averageRelevanceScore: 0,
        knowledgeGraphQueries: 0
      },
      performance: {
        memoryUsage: 0,
        contextLoadingTime: 0,
        ttlProcessingTime: 0,
        lastOptimization: new Date()
      }
    };
  }

  /**
   * Setup event handlers for integration
   */
  private setupEventHandlers(): void {
    // Handle TTL file changes
    this.ttlContextLoader.on('ttl_file_changed', (event: TTLIntegrationEvent) => {
      this.handleTTLFileChange(event);
    });
    
    // Handle TTL file refresh
    this.ttlContextLoader.on('ttl_file_refreshed', (event: TTLIntegrationEvent) => {
      this.handleTTLFileRefresh(event);
    });
    
    // Handle MCP server events
    this.mcpServer.on('ttl_file_changed', (event: any) => {
      this.emit('ttl_integration_update', event);
    });
  }

  /**
   * Start the enhanced MCP server
   */
  async start(): Promise<void> {
    try {
      logger.info('Starting Enhanced MCP Server...');
      
      // Start TTL context loader first
      await this.ttlContextLoader.start();
      
      // Override MCP server context generation with enhanced version
      this.enhanceMCPServerContextGeneration();
      
      // Start base MCP server
      await this.mcpServer.start();
      
      this.isRunning = true;
      
      logger.info('Enhanced MCP Server started successfully', {
        ttlFiles: this.ttlContextLoader.getTTLFiles().size,
        mcpServerRunning: true
      });
      
    } catch (error) {
      logger.error('Failed to start Enhanced MCP Server', { error });
      throw error;
    }
  }

  /**
   * Stop the enhanced MCP server
   */
  async stop(): Promise<void> {
    try {
      logger.info('Stopping Enhanced MCP Server...');
      
      this.isRunning = false;
      
      // Stop MCP server
      await this.mcpServer.stop();
      
      // Stop TTL context loader
      await this.ttlContextLoader.stop();
      
      logger.info('Enhanced MCP Server stopped');
      
    } catch (error) {
      logger.error('Failed to stop Enhanced MCP Server', { error });
      throw error;
    }
  }

  /**
   * Get enhanced context using TTL loader
   */
  async getEnhancedContext(request: ContextRequest): Promise<ContextResponse> {
    const startTime = Date.now();
    this.metrics.server.enhancedContextRequests++;
    
    try {
      // Use TTL context loader for enhanced context
      const response = await this.ttlContextLoader.loadContext(request);
      
      // Update metrics
      const processingTime = Date.now() - startTime;
      this.updateMetrics(processingTime, response);
      
      return response;
      
    } catch (error) {
      logger.error('Failed to get enhanced context', { request, error });
      this.metrics.server.errorRate++;
      throw error;
    }
  }

  /**
   * Refresh TTL files and update context
   */
  async refreshTTLContext(): Promise<void> {
    try {
      logger.info('Refreshing TTL context...');
      
      const ttlFiles = this.ttlContextLoader.getTTLFiles();
      const refreshPromises = Array.from(ttlFiles.keys()).map(path =>
        this.ttlContextLoader.refreshTTLFile(path)
      );
      
      await Promise.allSettled(refreshPromises);
      
      logger.info(`Refreshed ${ttlFiles.size} TTL files`);
      
    } catch (error) {
      logger.error('Failed to refresh TTL context', { error });
      throw error;
    }
  }

  /**
   * Get server status including TTL integration
   */
  getStatus(): any {
    const baseStatus = this.mcpServer.getStatus();
    const ttlMetrics = this.ttlContextLoader.getMetrics();
    
    return {
      ...baseStatus,
      enhanced: {
        isRunning: this.isRunning,
        ttlIntegration: {
          ttlFilesLoaded: ttlMetrics.ttlFiles.loaded,
          ttlFilesWatching: ttlMetrics.ttlFiles.watching,
          contextCacheSize: ttlMetrics.performance.cacheSize,
          lastCleanup: ttlMetrics.performance.lastCleanup
        },
        metrics: this.metrics
      }
    };
  }

  /**
   * Get enhanced metrics
   */
  getMetrics(): EnhancedMCPServerMetrics {
    const ttlMetrics = this.ttlContextLoader.getMetrics();
    
    // Update performance metrics
    this.metrics.performance.memoryUsage = process.memoryUsage().heapUsed;
    this.metrics.ttlIntegration.ttlFilesLoaded = ttlMetrics.ttlFiles.loaded;
    this.metrics.ttlIntegration.contextCacheHits = ttlMetrics.context.cacheHits;
    this.metrics.ttlIntegration.contextCacheMisses = ttlMetrics.context.cacheMisses;
    this.metrics.ttlIntegration.averageRelevanceScore = ttlMetrics.context.averageRelevanceScore;
    
    return { ...this.metrics };
  }

  /**
   * Get TTL files information
   */
  getTTLFiles(): Map<string, any> {
    return this.ttlContextLoader.getTTLFiles();
  }

  /**
   * Enhance MCP server context generation
   */
  private enhanceMCPServerContextGeneration(): void {
    // Override the generateContext method in MCPServer to use our enhanced loader
    const originalGenerateContext = (this.mcpServer as any).generateContext;
    
    (this.mcpServer as any).generateContext = async (request: ContextRequest): Promise<ContextResponse> => {
      try {
        // Try enhanced context first
        const enhancedResponse = await this.getEnhancedContext(request);
        this.metrics.server.ttlContextRequests++;
        return enhancedResponse;
        
      } catch (error) {
        logger.warn('Enhanced context failed, falling back to original', { error });
        // Fallback to original implementation
        return await originalGenerateContext.call(this.mcpServer, request);
      }
    };
    
    logger.info('MCP Server context generation enhanced with TTL integration');
  }

  /**
   * Handle TTL file change events
   */
  private handleTTLFileChange(event: TTLIntegrationEvent): void {
    logger.debug('TTL file changed', { 
      type: event.type, 
      path: event.path 
    });
    
    // Emit integration event
    this.emit('ttl_integration_update', {
      type: 'file_changed',
      data: event,
      timestamp: Date.now()
    });
    
    // Update metrics
    if (event.type === 'created') {
      this.metrics.ttlIntegration.ttlFilesLoaded++;
    }
  }

  /**
   * Handle TTL file refresh events
   */
  private handleTTLFileRefresh(event: TTLIntegrationEvent): void {
    logger.debug('TTL file refreshed', { path: event.path });
    
    // Emit integration event
    this.emit('ttl_integration_update', {
      type: 'file_refreshed',
      data: event,
      timestamp: Date.now()
    });
  }

  /**
   * Update metrics
   */
  private updateMetrics(processingTime: number, response: ContextResponse): void {
    const total = this.metrics.server.enhancedContextRequests;
    
    // Update average response time
    this.metrics.server.averageResponseTime =
      (this.metrics.server.averageResponseTime * (total - 1) + processingTime) / total;
    
    // Update context loading time
    this.metrics.performance.contextLoadingTime =
      (this.metrics.performance.contextLoadingTime * (total - 1) + processingTime) / total;
    
    // Update cache metrics
    if (response.metadata.cached) {
      this.metrics.ttlIntegration.contextCacheHits++;
    } else {
      this.metrics.ttlIntegration.contextCacheMisses++;
    }
  }

  /**
   * Optimize performance
   */
  async optimizePerformance(): Promise<void> {
    try {
      logger.info('Optimizing Enhanced MCP Server performance...');
      
      // Clear old cache entries
      const ttlMetrics = this.ttlContextLoader.getMetrics();
      if (ttlMetrics.performance.cacheSize > this.config.ttlContextLoader.maxCacheSize * 0.8) {
        // Trigger cache cleanup
        logger.info('Triggering cache cleanup for performance optimization');
      }
      
      // Update optimization timestamp
      this.metrics.performance.lastOptimization = new Date();
      
      logger.info('Performance optimization completed');
      
    } catch (error) {
      logger.error('Failed to optimize performance', { error });
    }
  }

  /**
   * Health check for the enhanced server
   */
  async healthCheck(): Promise<{
    status: 'healthy' | 'degraded' | 'unhealthy';
    details: Record<string, any>;
  }> {
    try {
      const baseStatus = this.mcpServer.getStatus();
      const ttlMetrics = this.ttlContextLoader.getMetrics();
      
      let status: 'healthy' | 'degraded' | 'unhealthy' = 'healthy';
      const details: Record<string, any> = {
        mcpServer: baseStatus.status,
        ttlLoader: {
          filesLoaded: ttlMetrics.ttlFiles.loaded,
          filesFailed: ttlMetrics.ttlFiles.failed,
          cacheSize: ttlMetrics.performance.cacheSize
        },
        performance: {
          memoryUsage: process.memoryUsage().heapUsed,
          uptime: baseStatus.uptime
        }
      };
      
      // Check for degraded performance
      if (ttlMetrics.ttlFiles.failed > ttlMetrics.ttlFiles.loaded * 0.1) {
        status = 'degraded';
        details.warning = 'High TTL file loading failure rate';
      }
      
      // Check for unhealthy state
      if (baseStatus.status !== 'running' || !this.isRunning) {
        status = 'unhealthy';
        details.error = 'Server not running';
      }
      
      return { status, details };
      
    } catch (error) {
      logger.error('Health check failed', { error });
      return {
        status: 'unhealthy',
        details: { error: error instanceof Error ? error.message : String(error) }
      };
    }
  }
}