/**
 * Git Hooks Manager
 * 
 * Manages Git hooks for TTL file versioning and automatic re-analysis
 * when TTL files are modified by developers.
 */

import { EventEmitter } from 'events';
import { writeFile, mkdir, chmod, readFile, stat } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import simpleGit, { SimpleGit } from 'simple-git';
import logger from '../../utils/logger';

export interface GitHookConfig {
  projectRoot: string;
  ttlDirectories: string[];
  ttlPatterns: string[];
  enablePreCommitHook: boolean;
  enablePostCommitHook: boolean;
  enablePostMergeHook: boolean;
  autoReanalyzeOnTTLChange: boolean;
}

export interface TTLFileChange {
  filePath: string;
  changeType: 'added' | 'modified' | 'deleted';
  timestamp: Date;
  commitHash?: string;
  author?: string;
}

export interface GitHookEvent {
  type: 'pre-commit' | 'post-commit' | 'post-merge';
  ttlChanges: TTLFileChange[];
  timestamp: Date;
  commitHash?: string;
}

/**
 * Git Hooks Manager for TTL File Versioning
 */
export class GitHooksManager extends EventEmitter {
  private config: GitHookConfig;
  private git: SimpleGit;
  private isInitialized = false;

  constructor(config: GitHookConfig) {
    super();
    this.config = config;
    this.git = simpleGit(config.projectRoot);
  }

  /**
   * Initialize Git hooks for TTL file monitoring
   */
  async initialize(): Promise<void> {
    if (this.isInitialized) {
      return;
    }

    try {
      logger.info('🔧 Initializing Git hooks for TTL file versioning...');

      // Check if we're in a Git repository
      const isRepo = await this.git.checkIsRepo();
      if (!isRepo) {
        logger.warn('⚠️  Not a Git repository - Git hooks will not be installed');
        return;
      }

      // Create .git/hooks directory if it doesn't exist
      const hooksDir = join(this.config.projectRoot, '.git', 'hooks');
      await mkdir(hooksDir, { recursive: true });

      // Install hooks based on configuration
      if (this.config.enablePreCommitHook) {
        await this.installPreCommitHook(hooksDir);
      }

      if (this.config.enablePostCommitHook) {
        await this.installPostCommitHook(hooksDir);
      }

      if (this.config.enablePostMergeHook) {
        await this.installPostMergeHook(hooksDir);
      }

      this.isInitialized = true;
      logger.info('✅ Git hooks initialized successfully');

    } catch (error) {
      logger.error('❌ Failed to initialize Git hooks', { error });
      throw error;
    }
  }

  /**
   * Install pre-commit hook to validate TTL files before commit
   */
  private async installPreCommitHook(hooksDir: string): Promise<void> {
    const hookPath = join(hooksDir, 'pre-commit');
    
    const hookScript = `#!/bin/sh
# AASWE Pre-commit Hook - TTL File Validation
# Auto-generated by AASWE Git Hooks Manager

echo "🔍 AASWE: Checking TTL files before commit..."

# Get staged TTL files
STAGED_TTL_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\\.(ttl|module-knowledge\\.ttl)$" || true)

if [ -n "$STAGED_TTL_FILES" ]; then
  echo "📝 Found staged TTL files:"
  echo "$STAGED_TTL_FILES"
  
  # Validate TTL files
  node -e "
    const { GitHooksManager } = require('./dist/services/git-integration/GitHooksManager');
    const manager = new GitHooksManager({
      projectRoot: process.cwd(),
      ttlDirectories: ['./knowledge', './clean-knowledge', './.aaswe/knowledge'],
      ttlPatterns: ['**/*.ttl', '**/*.module-knowledge.ttl'],
      enablePreCommitHook: true,
      enablePostCommitHook: true,
      enablePostMergeHook: true,
      autoReanalyzeOnTTLChange: true
    });
    manager.validateStagedTTLFiles().then(valid => {
      if (!valid) {
        console.error('❌ TTL file validation failed');
        process.exit(1);
      }
      console.log('✅ TTL files validated successfully');
    }).catch(err => {
      console.error('❌ TTL validation error:', err.message);
      process.exit(1);
    });
  "
  
  if [ $? -ne 0 ]; then
    echo "❌ Pre-commit hook failed - TTL file validation errors"
    exit 1
  fi
fi

echo "✅ AASWE: Pre-commit checks passed"
exit 0
`;

    await writeFile(hookPath, hookScript);
    await chmod(hookPath, 0o755);
    logger.info('✅ Pre-commit hook installed');
  }

  /**
   * Install post-commit hook to trigger re-analysis after TTL changes
   */
  private async installPostCommitHook(hooksDir: string): Promise<void> {
    const hookPath = join(hooksDir, 'post-commit');
    
    const hookScript = `#!/bin/sh
# AASWE Post-commit Hook - TTL File Re-analysis
# Auto-generated by AASWE Git Hooks Manager

echo "🔄 AASWE: Checking for TTL file changes in commit..."

# Get TTL files changed in the last commit
CHANGED_TTL_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD | grep -E "\\.(ttl|module-knowledge\\.ttl)$" || true)

if [ -n "$CHANGED_TTL_FILES" ]; then
  echo "📝 TTL files changed in commit:"
  echo "$CHANGED_TTL_FILES"
  
  # Trigger re-analysis in background
  echo "🚀 Triggering automatic re-analysis..."
  nohup node -e "
    const { GitHooksManager } = require('./dist/services/git-integration/GitHooksManager');
    const manager = new GitHooksManager({
      projectRoot: process.cwd(),
      ttlDirectories: ['./knowledge', './clean-knowledge', './.aaswe/knowledge'],
      ttlPatterns: ['**/*.ttl', '**/*.module-knowledge.ttl'],
      enablePreCommitHook: true,
      enablePostCommitHook: true,
      enablePostMergeHook: true,
      autoReanalyzeOnTTLChange: true
    });
    manager.handlePostCommitReanalysis().catch(console.error);
  " > /dev/null 2>&1 &
  
  echo "✅ AASWE: Re-analysis triggered in background"
else
  echo "ℹ️  AASWE: No TTL files changed in this commit"
fi

exit 0
`;

    await writeFile(hookPath, hookScript);
    await chmod(hookPath, 0o755);
    logger.info('✅ Post-commit hook installed');
  }

  /**
   * Install post-merge hook to handle TTL conflicts and re-analysis
   */
  private async installPostMergeHook(hooksDir: string): Promise<void> {
    const hookPath = join(hooksDir, 'post-merge');
    
    const hookScript = `#!/bin/sh
# AASWE Post-merge Hook - TTL File Conflict Resolution
# Auto-generated by AASWE Git Hooks Manager

echo "🔀 AASWE: Checking for TTL file changes after merge..."

# Check if merge brought in TTL file changes
MERGED_TTL_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD~1..HEAD | grep -E "\\.(ttl|module-knowledge\\.ttl)$" || true)

if [ -n "$MERGED_TTL_FILES" ]; then
  echo "📝 TTL files affected by merge:"
  echo "$MERGED_TTL_FILES"
  
  # Trigger conflict resolution and re-analysis
  echo "🔧 Resolving TTL conflicts and triggering re-analysis..."
  node -e "
    const { GitHooksManager } = require('./dist/services/git-integration/GitHooksManager');
    const manager = new GitHooksManager({
      projectRoot: process.cwd(),
      ttlDirectories: ['./knowledge', './clean-knowledge', './.aaswe/knowledge'],
      ttlPatterns: ['**/*.ttl', '**/*.module-knowledge.ttl'],
      enablePreCommitHook: true,
      enablePostCommitHook: true,
      enablePostMergeHook: true,
      autoReanalyzeOnTTLChange: true
    });
    manager.handlePostMergeReanalysis().catch(console.error);
  "
  
  echo "✅ AASWE: Post-merge processing completed"
else
  echo "ℹ️  AASWE: No TTL files affected by merge"
fi

exit 0
`;

    await writeFile(hookPath, hookScript);
    await chmod(hookPath, 0o755);
    logger.info('✅ Post-merge hook installed');
  }

  /**
   * Validate staged TTL files before commit
   */
  async validateStagedTTLFiles(): Promise<boolean> {
    try {
      const stagedFiles = await this.git.diff(['--cached', '--name-only']);
      const ttlFiles = stagedFiles.split('\n').filter(file => 
        file.match(/\.(ttl|module-knowledge\.ttl)$/)
      );

      if (ttlFiles.length === 0) {
        return true; // No TTL files to validate
      }

      logger.info(`🔍 Validating ${ttlFiles.length} staged TTL files...`);

      for (const filePath of ttlFiles) {
        const fullPath = join(this.config.projectRoot, filePath);
        
        if (!existsSync(fullPath)) {
          continue; // File was deleted
        }

        try {
          const content = await readFile(fullPath, 'utf-8');
          const isValid = await this.validateTTLContent(content, filePath);
          
          if (!isValid) {
            logger.error(`❌ Invalid TTL file: ${filePath}`);
            return false;
          }
        } catch (error) {
          logger.error(`❌ Error validating TTL file ${filePath}:`, error);
          return false;
        }
      }

      logger.info('✅ All staged TTL files are valid');
      return true;

    } catch (error) {
      logger.error('❌ Failed to validate staged TTL files', { error });
      return false;
    }
  }

  /**
   * Handle post-commit re-analysis
   */
  async handlePostCommitReanalysis(): Promise<void> {
    try {
      const commitHash = await this.git.revparse(['HEAD']);
      const changedFiles = await this.getChangedTTLFiles(commitHash);

      if (changedFiles.length === 0) {
        return;
      }

      logger.info(`🔄 Post-commit: Re-analyzing ${changedFiles.length} TTL files...`);

      const event: GitHookEvent = {
        type: 'post-commit',
        ttlChanges: changedFiles,
        timestamp: new Date(),
        commitHash
      };

      this.emit('git-hook-event', event);

      if (this.config.autoReanalyzeOnTTLChange) {
        await this.triggerReanalysis(changedFiles);
      }

    } catch (error) {
      logger.error('❌ Post-commit re-analysis failed', { error });
    }
  }

  /**
   * Handle post-merge re-analysis and conflict resolution
   */
  async handlePostMergeReanalysis(): Promise<void> {
    try {
      const commitHash = await this.git.revparse(['HEAD']);
      const changedFiles = await this.getChangedTTLFiles(commitHash, 'HEAD~1..HEAD');

      if (changedFiles.length === 0) {
        return;
      }

      logger.info(`🔀 Post-merge: Processing ${changedFiles.length} TTL files...`);

      // Check for merge conflicts in TTL files
      const conflictedFiles = await this.detectTTLConflicts(changedFiles);
      
      if (conflictedFiles.length > 0) {
        logger.warn(`⚠️  Detected ${conflictedFiles.length} TTL files with potential conflicts`);
        await this.resolveTTLConflicts(conflictedFiles);
      }

      const event: GitHookEvent = {
        type: 'post-merge',
        ttlChanges: changedFiles,
        timestamp: new Date(),
        commitHash
      };

      this.emit('git-hook-event', event);

      if (this.config.autoReanalyzeOnTTLChange) {
        await this.triggerReanalysis(changedFiles);
      }

    } catch (error) {
      logger.error('❌ Post-merge re-analysis failed', { error });
    }
  }

  /**
   * Get changed TTL files from a commit
   */
  private async getChangedTTLFiles(commitHash: string, range?: string): Promise<TTLFileChange[]> {
    try {
      const diffArgs = range ? [range] : ['--name-status', `${commitHash}~1..${commitHash}`];
      const diff = await this.git.diff(diffArgs);
      
      const changes: TTLFileChange[] = [];
      const lines = diff.split('\n').filter(line => line.trim());

      for (const line of lines) {
        const [status, filePath] = line.split('\t');
        
        if (filePath && filePath.match(/\.(ttl|module-knowledge\.ttl)$/)) {
          let changeType: 'added' | 'modified' | 'deleted';
          
          switch (status) {
            case 'A':
              changeType = 'added';
              break;
            case 'D':
              changeType = 'deleted';
              break;
            default:
              changeType = 'modified';
          }

          changes.push({
            filePath,
            changeType,
            timestamp: new Date(),
            commitHash
          });
        }
      }

      return changes;
    } catch (error) {
      logger.error('❌ Failed to get changed TTL files', { error });
      return [];
    }
  }

  /**
   * Validate TTL content
   */
  private async validateTTLContent(content: string, filePath: string): Promise<boolean> {
    try {
      // Basic TTL syntax validation
      const lines = content.split('\n');
      let hasValidTriples = false;

      for (const line of lines) {
        const trimmed = line.trim();
        
        // Skip empty lines and comments
        if (!trimmed || trimmed.startsWith('#')) continue;
        
        // Check for basic triple structure
        if (trimmed.includes(' ') && (trimmed.endsWith('.') || trimmed.endsWith(';'))) {
          hasValidTriples = true;
        } else if (trimmed.length > 0) {
          logger.warn(`⚠️  Potential syntax issue in ${filePath}: ${trimmed}`);
        }
      }

      if (!hasValidTriples) {
        logger.error(`❌ No valid triples found in ${filePath}`);
        return false;
      }

      return true;
    } catch (error) {
      logger.error(`❌ TTL validation error for ${filePath}:`, error);
      return false;
    }
  }

  /**
   * Detect TTL conflicts after merge
   */
  private async detectTTLConflicts(changedFiles: TTLFileChange[]): Promise<string[]> {
    const conflictedFiles: string[] = [];

    for (const change of changedFiles) {
      const fullPath = join(this.config.projectRoot, change.filePath);
      
      if (!existsSync(fullPath)) continue;

      try {
        const content = await readFile(fullPath, 'utf-8');
        
        // Check for Git conflict markers
        if (content.includes('<<<<<<<') || content.includes('>>>>>>>') || content.includes('=======')) {
          conflictedFiles.push(change.filePath);
        }
      } catch (error) {
        logger.error(`❌ Error checking conflicts in ${change.filePath}:`, error);
      }
    }

    return conflictedFiles;
  }

  /**
   * Resolve TTL conflicts by triggering re-analysis
   */
  private async resolveTTLConflicts(conflictedFiles: string[]): Promise<void> {
    logger.info(`🔧 Resolving conflicts in ${conflictedFiles.length} TTL files...`);
    
    // For now, log the conflicts and suggest manual resolution
    // In a full implementation, this could trigger automatic re-analysis
    // to regenerate clean TTL files
    
    for (const filePath of conflictedFiles) {
      logger.warn(`⚠️  Manual resolution required for: ${filePath}`);
      logger.info(`💡 Consider running: aaswe analyze --output ${filePath.split('/')[0]}`);
    }
  }

  /**
   * Trigger re-analysis for changed TTL files
   */
  private async triggerReanalysis(changedFiles: TTLFileChange[]): Promise<void> {
    try {
      logger.info(`🚀 Triggering re-analysis for ${changedFiles.length} changed TTL files...`);

      // Import and run the AutoAnalysisWorkflow
      const { AutoAnalysisWorkflow } = await import('../project-analysis/AutoAnalysisWorkflow');
      
      const workflow = new AutoAnalysisWorkflow({
        projectRoot: this.config.projectRoot,
        outputDirectory: join(this.config.projectRoot, 'knowledge'),
        languages: ['typescript', 'javascript', 'python', 'java'],
        preserveBusinessContext: true,
        enableKnowledgeGraphPopulation: false, // Git hook mode
        enableMCPContextLoading: false // Git hook mode
      });

      const result = await workflow.executeComprehensiveAnalysis();
      
      logger.info('✅ Re-analysis completed successfully', {
        filesAnalyzed: result.summary.analyzedFiles,
        ttlFilesGenerated: result.summary.ttlFilesGenerated,
        executionTime: `${result.duration}ms`
      });

    } catch (error) {
      logger.error('❌ Re-analysis failed', { error });
    }
  }

  /**
   * Uninstall Git hooks
   */
  async uninstall(): Promise<void> {
    try {
      const hooksDir = join(this.config.projectRoot, '.git', 'hooks');
      const hooks = ['pre-commit', 'post-commit', 'post-merge'];

      for (const hook of hooks) {
        const hookPath = join(hooksDir, hook);
        
        if (existsSync(hookPath)) {
          try {
            const content = await readFile(hookPath, 'utf-8');
            
            // Only remove if it's our hook
            if (content.includes('AASWE Git Hooks Manager')) {
              await writeFile(hookPath + '.backup', content);
              // Remove the hook file or replace with backup if it existed
              logger.info(`✅ Uninstalled ${hook} hook (backup created)`);
            }
          } catch (error) {
            logger.warn(`⚠️  Could not uninstall ${hook} hook:`, error);
          }
        }
      }

      logger.info('✅ Git hooks uninstalled successfully');
    } catch (error) {
      logger.error('❌ Failed to uninstall Git hooks', { error });
    }
  }

  /**
   * Get Git hooks status
   */
  async getStatus(): Promise<any> {
    try {
      const hooksDir = join(this.config.projectRoot, '.git', 'hooks');
      const hooks = ['pre-commit', 'post-commit', 'post-merge'];
      const status: any = {
        isGitRepo: await this.git.checkIsRepo(),
        hooksInstalled: {},
        lastActivity: null
      };

      for (const hook of hooks) {
        const hookPath = join(hooksDir, hook);
        
        if (existsSync(hookPath)) {
          const stats = await stat(hookPath);
          const content = await readFile(hookPath, 'utf-8');
          
          status.hooksInstalled[hook] = {
            exists: true,
            isAASWE: content.includes('AASWE Git Hooks Manager'),
            lastModified: stats.mtime,
            executable: (stats.mode & 0o111) !== 0
          };
        } else {
          status.hooksInstalled[hook] = {
            exists: false,
            isAASWE: false
          };
        }
      }

      return status;
    } catch (error) {
      logger.error('❌ Failed to get Git hooks status', { error });
      return { error: error instanceof Error ? error.message : 'Unknown error' };
    }
  }
}